Re-establish context if no longer available.
Yubico/yubico-piv-tool pull request #332
Opened 2021-11-08 22:52 UTC by qpernil

Requires remembering the reader name. Should also check serial number

2021-11-09 22:10 UTC, qpernil commented
With the latest change here it also works fine on Windows. If you remove the last reader on Windows the context becomes invalid, something that I haven't seen happen at all on other platforms

2021-12-13 09:13 UTC, aveenismail requested changes

2021-12-13 09:13 UTC, aveenismail commented on common/util.c
> +  name[sizeof(name) - 1] = 0;
Is setting the last byte to 0 really necessary? `name` is 1025 chars, all set to 0 at initialization. If `orig_name` is more that 1024 chars long, and error will be thrown and name will not be set. So at this line, `name` already is null terminated

2021-12-13 10:03 UTC, aveenismail approved these changes

2021-12-13 12:48 UTC, merged